name: WOG Flutter Build & Preview

on:
  push:
    branches: [ "main" ]

# GitHub Pages కి పర్మిషన్స్
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      
      # Build Commands
      - run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"
      - run: flutter build apk --release
      - run: flutter build appbundle --release

      # 1. Upload Artifacts (Downloadable APK/AAB)
      - uses: actions/upload-artifact@v3
        with:
          name: WOG-APK
          path: build/app/outputs/flutter-apk/app-release.apk
      - uses: actions/upload-artifact@v3
        with:
          name: WOG-AAB
          path: build/app/outputs/bundle/release/app-release.aab

      # 2. Deploy to GitHub Pages (For Live Preview)
      - name: Deploy Web to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web